FROM mhart/alpine-node:14.16.1 as builder

WORKDIR /App

COPY package.json  .

RUN npm install 

COPY . .

RUN npm run build --prod;


#  setingup  the server 

FROM nginx:1.21.6-alpine

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /App/public  /var/www

EXPOSE 4200

ENTRYPOINT [ "nginx" ,"-g" ,"daemon off;" ]

