#  setingup  the server 

FROM nginx:1.21.6-alpine

WORKDIR /App

COPY package.json  .

RUN npm install 

COPY . .

RUN npm run build;

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 4200

ENTRYPOINT [ "nginx" ,"-g" ,"daemon off;" ]

