version: "3.8"
services:
  database:
    image: mysql:8.0
    container_name: database_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop
    volumes:
      - D:/mysqlData:/var/lib/mysql
  server:
    build: ./server
    container_name: server_container
    ports:
      - 8090:8090
    depends_on:
      - database
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - 80:80
    depends_on:
      - server
