version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: doodleblue
      MYSQL_DATABASE: shop
    volumes:
      - D:/mysqlData:/var/lib/mysql
  server:
    build: ./server
    container_name: server_container
    ports:
      - 8090:8090
    depends_on:
      - database
  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - 4200:4200
    depends_on:
      - server
