# This is a basic workflow to help you get started with Actions

name: Continues & Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "connect with ec2 Server"
  job_one:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: connect to server Perform deployment operation
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.HOME_KEY }}
          port: 22
          script: |
            cd /home/${USER}
            rm -rfv ecommerce
            sleep 60
            echo "started cloning"
            git clone https://github.com/Arun-2095/ecommerce.git
            cd ecommerce
            docker-compose down
            docker system prune -f
            docker-compose build 
            APP_VOLUME=/home/${USER}/appDataBase docker-compose up
