# This is a basic workflow to help you get started with Actions

name: Continues & Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull  request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "connect with ec2 Server"
  job_one:
    name: Deploy on live
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: connect to server Perform deployment operations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.HOME_KEY }}
          port: 22
          envs: PROD
          script: |
            cd /home/${USER}/ecommerce
            echo -e "\033[1;31mstarted pull latest updates\033[0m\n"
            git pull 
            echo -e "\033[1;31mRemoving Previous Docker container\033[0m\n"
            docker-compose down
            docker system prune -f
            echo -e "\033[1;31mBuilding Images \033[0m\n"
            docker-compose build 
            echo -e "\033[1;31mCreating the container  \033[0m\n"
            APP_VOLUME=/home/${USER}/appDataBase docker-compose up -d
            echo -e "\033[1;32mDeployment Completed  \033[0m\n"
            exit
